# SPDX-FileCopyrightText: 2024 BombasterDS <115770678+BombasterDS@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: securityIcon
  id: MindShieldBrokenIcon
  priority: 2
  locationPreference: Right
  layer: Mod
  isShaded: true
  icon:
    sprite: /Textures/_Goobstation/Interface/Misc/security_icons.rsi
    state: MindShield-broken

- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconPerma
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_perma

- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconSearch
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_search
