- type: antag
  id: Survivor
  name: roles-antag-survivor-name
  antagonist: true
  objective: roles-antag-survivor-objective
  # guides: [  ]

- type: antag
  id: Wizard
  name: roles-antag-wizard-name
  antagonist: true
  setPreference: true
  objective: roles-antag-wizard-description # Goob
  requirements: # I hate time locked roles but this should be enough time for someone to be acclimated
  - !type:OverallPlaytimeRequirement
    time: 35h # Goob - was 5h
  - !type:SpeciesRequirement # Goob
    inverted: true
    species:
    - Plasmaman
  guides: [ Wizard ]

# See wizard_startinggear for wiz start gear options
